version: "3"
services: 
  factorio:
    image: factoriotools/factorio:latest
    ports:
      - "34197:34197/udp"
    volumes:
    - factorio:/factorio
    - ./data/config/server-settings.json:/server-settings.json
    environment:
      - INSTANCE_NAME=Skullgames
      - INSTANCE_DESC=MultiClan-Server
    entrypoint: /bin/sh -c "mkdir -p /factorio/config && envsubst < /server-settings.json > /factorio/config/server-settings.json && exec /docker-entrypoint.sh"

  dropbox:
    image: rbonghi/dropbox:latest
    environment:
      - PYTHONUNBUFFERED=1
      - DROPBOX_TOKEN=${DROPBOXTOKEN}
    volumes:
      - factorio:/dropbox

volumes:
  factorio: